alias ll="ls -al --color=tty"
alias l.="ls -l"
alias vi="vim"
alias cd..="cd .."
alias h="history"
alias grep="grep --color=auto"
alias cls="clear"
alias rm="rm -i"
alias cp="cp -i"
alias mv="mv -i"
alias mysqlr="mysql -u root -p"
alias openmysql="sudo systemctl start mysqld"
alias closemysql="sudo systemctl stop mysqld"
alias flushcache="echo 3 > /proc/sys/vm/drop_caches"
alias reswap="sudo swapoff -a;sudo swapon -a"

PS1="\s-\v \u:\W> "
