#!/bin/bash

# This way you can customize which branches should be skipped when
# prepending commit message. 
if [ -z "$PREFIX_TO_SKIP" ]; then
    PREFIX_TO_SKIP="Feature BugFix Optimize Refactor"                                                                                            
fi

PREFIX_NAME="Feature"
PREFIX_IN_COMMIT=0

for prefix in $PREFIX_TO_SKIP
do
    echo "$prefix:$PREFIX_IN_COMMIT"
    PREFIX_IN_COMMIT=$(($PREFIX_IN_COMMIT+$(grep -c "$prefix" $1)))
done

if [ -n "$PREFIX_NAME" ] && ! [[ $PREFIX_IN_COMMIT -ge 1 ]]; then 
    sed -i.bak -e "1s/^/$PREFIX_NAME:/" $1
fi

